import { Ticket, KBArticle, NotificationRule } from "./types";

export const mockTickets: Ticket[] = [
  {
    id: "TKT-001",
    userId: "user1",
    userName: "John Doe",
    userEmail: "john@example.com",
    category: "Network",
    subCategory: "VPN",
    description: "Cannot connect to VPN from home",
    status: "open",
    priority: "high",
    createdAt: "2025-01-15T09:30:00Z",
    updatedAt: "2025-01-15T09:30:00Z",
    assignedTeam: "Network Team",
    slaDue: "2025-01-16T09:30:00Z",
  },
  {
    id: "TKT-002",
    userId: "user2",
    userName: "Jane Smith",
    userEmail: "jane@example.com",
    category: "Authentication",
    subCategory: "Password Reset",
    description: "Forgot password, need reset",
    status: "in-progress",
    priority: "medium",
    createdAt: "2025-01-14T14:20:00Z",
    updatedAt: "2025-01-15T10:15:00Z",
    assignedTeam: "Security Team",
  },
  {
    id: "TKT-003",
    userId: "user3",
    userName: "Bob Johnson",
    userEmail: "bob@example.com",
    category: "Hardware",
    subCategory: "Laptop",
    description: "Laptop screen flickering",
    status: "resolved",
    priority: "low",
    createdAt: "2025-01-13T11:00:00Z",
    updatedAt: "2025-01-14T16:45:00Z",
    assignedTeam: "Hardware Team",
  },
];

export const mockKBArticles: KBArticle[] = [
  {
    id: "KB-001",
    title: "How to Reset Your Password",
    category: "Authentication",
    tags: ["password", "security", "login"],
    content: "Step-by-step guide to reset your password...",
    status: "published",
    updatedAt: "2025-01-10T10:00:00Z",
    views: 245,
  },
  {
    id: "KB-002",
    title: "VPN Connection Troubleshooting",
    category: "Network",
    tags: ["vpn", "network", "connection"],
    content: "Common VPN issues and how to fix them...",
    status: "published",
    updatedAt: "2025-01-12T14:30:00Z",
    views: 182,
  },
  {
    id: "KB-003",
    title: "Laptop Hardware Diagnostics",
    category: "Hardware",
    tags: ["laptop", "diagnostics", "troubleshooting"],
    content: "How to diagnose common laptop hardware issues...",
    status: "draft",
    updatedAt: "2025-01-14T09:15:00Z",
    views: 0,
  },
];

export const mockNotificationRules: NotificationRule[] = [
  {
    id: "RULE-001",
    name: "High Priority Alert",
    event: "Ticket Created",
    condition: "priority = high",
    channel: ["Email", "Slack"],
    recipients: "admin@example.com",
    active: true,
  },
  {
    id: "RULE-002",
    name: "SLA Breach Warning",
    event: "SLA Near Breach",
    condition: "time_remaining < 2h",
    channel: ["Email", "SMS"],
    recipients: "team-leads@example.com",
    active: true,
  },
];
